name: 'Action Approval new'

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: "qc"
        type: choice
        options:
          - qc
          - preview
          - prod

jobs:
  qc:
    runs-on: 'ubuntu-latest'
    environment: 'qc'
    if: ${{ github.event.inputs.environment == 'qc' }}
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests

    - name: Build the artifact
      run: |
        echo "Deploying the application on the dev environment."
    
    - name: Run Template Loader script
      working-directory: ./setup
      run: |
        python -u template-loader.py
      env:
        PARTNER_API_KEY: ${{ secrets.PARTNER_API_KEY }}
        VALUES_FILE: "./values-qc.yaml"
  
  preview:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    if: ${{ github.event.inputs.environment == 'preview' }}
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests

    - name: Build the artifact
      run: |
        echo "Deploying the application on the dev environment."
  
    - name: Run Template Loader script
      working-directory: ./setup
      run: |
        python -u template-loader.py
      env:
        PARTNER_API_KEY: ${{ secrets.PARTNER_API_KEY }}
        VALUES_FILE: "./values-preview.yaml"
  
  prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    if: ${{ github.event.inputs.environment == 'prod' }}
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Template Loader script
      working-directory: ./setup
      run: |
        python -u template-loader.py
      env:
        PARTNER_API_KEY: ${{ secrets.PARTNER_API_KEY }}
        VALUES_FILE: "./values-prod.yaml"