name: 'Action Approval'

on:
  push:
    branches:
      - "main"
      - "v*.*.*"
    # paths:
    #   - 'core-dev.yaml'
    #   - 'core-stg.yaml'
    #   - 'core-prod.yaml'
    #   - 'os-dev.yaml'
    #   - 'os-stg.yaml'
    #   - 'os-prod.yaml'
    #   - 'artifact-prod.yaml'
    #   - 'artifact-dev.yaml'
    #   - 'artifact-stg.yaml'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build the artifact
        run: |
          echo "Building the application"

      - name: Check changed files
        run: |
          echo "${{ join(github.event.head_commit.modified, ', ') }}"
      

  dev:
    runs-on: 'ubuntu-latest'
    environment: 'dev'
    needs: build
    steps:

      - name: Build the artifact
        run: |
          echo "Deploying the application on the dev environment."

  prod:
    runs-on: 'ubuntu-latest'
    environment: 'prod'
    needs: [build, dev]
    steps:

      - name: Build the artifact
        run: |
          echo "Deploying the application on the prod environment."